# Generated by Django 3.0.5 on 2020-12-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointment_request_date',
            field=models.DateTimeField(),
        ),
    ]
